import type { Brand } from "./_brand.ts";
import { LogicError } from "./_error.ts";
import { HashTable } from "./_hashtable.ts";
import { idGenerator } from "./_idgenerator.ts";
import { fmix32, mixWord } from "./_murmurhash.ts";

export type ProcID = Brand<number, "procID">;
export type DataID = Brand<number, "dataID">;
export type DataVersion = Brand<number, "dataVersion">;
export type InvocationID = Brand<number, "invocationID">;

export const generateProcID: () => ProcID = idGenerator((x: number) =>
  x as ProcID
);

// Negative values are sentinels and never valid resolved IDs/versions.
// Real versions are positive and split into two disjoint namespaces so that
// a caller-managed number can never be mistaken for a generated one:
// versions generated by the run counter are even, and caller-managed source
// versions are mapped to odd values by versionToSourceDataVersion.

// "Unresolved" values are used for intermediate data nodes. An unresolved
// version acts as a wildcard when matching recorded output versions.
export const unresolvedIntermediateDataID = -1 as DataID;
export const unresolvedIntermediateDataVersion = -1 as DataVersion;
// A version for data whose current content is unknown (e.g. a destination
// whose version is not supplied). It never matches any recorded version.
export const unknownDataVersion = -2 as DataVersion;
// A version for data that must be considered changed every time (e.g. a
// source whose version is not supplied). It never equals any version,
// including itself.
export const alwaysChangedDataVersion = -3 as DataVersion;

/**
 * Maps a caller-managed source version (a non-negative integer) into the
 * graph's version namespace. The mapping is injective onto odd numbers while
 * generated versions are even, so a caller-chosen number can never collide
 * with a version generated by the graph. Exact for versions below 2^52.
 * @param version The caller-managed version.
 * @returns The version in the graph's namespace.
 */
export function versionToSourceDataVersion(version: number): DataVersion {
  return (version * 2 + 1) as DataVersion;
}

function runIndexToOutputDataVersion(runIndex: number): DataVersion {
  return (runIndex * 2) as DataVersion;
}

function matchUnresolvedVersion(
  unresolved: DataVersion,
  resolved: DataVersion,
): boolean {
  if (unresolved === unresolvedIntermediateDataVersion) {
    return true;
  }
  if (unresolved < 0 || resolved < 0) {
    return false;
  }

  return unresolved === resolved;
}

function matchUnresolvedVersionArray(
  unresolved: readonly DataVersion[],
  resolved: readonly DataVersion[],
): boolean {
  if (unresolved.length !== resolved.length) {
    return false;
  }

  for (let i = 0; i < unresolved.length; i++) {
    if (!matchUnresolvedVersion(unresolved[i], resolved[i])) {
      return false;
    }
  }

  return true;
}

function equalsVersionArray(
  l: readonly DataVersion[],
  r: readonly DataVersion[],
): boolean {
  if (l.length !== r.length) {
    return false;
  }

  for (let i = 0; i < l.length; i++) {
    // Negative versions are sentinels and never equal anything.
    if (l[i] < 0 || r[i] < 0 || l[i] !== r[i]) {
      return false;
    }
  }

  return true;
}

/**
 * An identity of an invocation across runs: which proc was applied to which
 * data nodes, and which providers back its intermediate outputs. Output IDs
 * of intermediate data are unresolved (-1) here so that resubmissions of the
 * same wiring find the same record; their provider IDs distinguish wirings
 * whose outputs are allocated differently, because a different provider can
 * change the produced content (e.g. the shape of the output buffer).
 */
export type InvocationSignature = {
  procID: ProcID;
  inputIDs: readonly DataID[];
  outputIDs: readonly DataID[];
  providerIDs: readonly DataID[];
};

function hashInvocationSignature(x: InvocationSignature): number {
  let h = 0;
  h = mixWord(h, x.procID | 0);
  for (const inputID of x.inputIDs) {
    h = mixWord(h, inputID | 0);
  }
  for (const outputID of x.outputIDs) {
    h = mixWord(h, outputID | 0);
  }
  for (const providerID of x.providerIDs) {
    h = mixWord(h, providerID | 0);
  }
  return fmix32(h);
}

function equalsInvocationSignature(
  l: InvocationSignature,
  r: InvocationSignature,
): boolean {
  if (l.procID !== r.procID) {
    return false;
  }

  if (l.inputIDs.length != r.inputIDs.length) {
    return false;
  }
  for (let i = 0; i < l.inputIDs.length; i++) {
    if (l.inputIDs[i] !== r.inputIDs[i]) {
      return false;
    }
  }

  if (l.outputIDs.length != r.outputIDs.length) {
    return false;
  }
  for (let i = 0; i < l.outputIDs.length; i++) {
    if (l.outputIDs[i] !== r.outputIDs[i]) {
      return false;
    }
  }

  if (l.providerIDs.length != r.providerIDs.length) {
    return false;
  }
  for (let i = 0; i < l.providerIDs.length; i++) {
    if (l.providerIDs[i] !== r.providerIDs[i]) {
      return false;
    }
  }

  return true;
}

/**
 * An invocation to resolve against the graph. Output IDs and versions of
 * intermediate data are unresolved (-1); versions of destinations are the
 * versions of their current content as known by the caller, or unknown (-2).
 * Provider IDs identify the provide functions of intermediate outputs;
 * destination outputs use -1 there.
 */
export type InvocationDraft = {
  procID: ProcID;
  inputIDs: readonly DataID[];
  inputVersions: readonly DataVersion[];
  outputIDs: readonly DataID[];
  outputVersions: readonly DataVersion[];
  providerIDs: readonly DataID[];
};

/**
 * The result of resolving an invocation draft. When `unchanged` is true, the
 * invocation would produce outputs identical to the content the recorded
 * versions describe, so executing it is unnecessary as long as that content
 * is still available.
 */
export type ResolvedInvocation = {
  outputIDs: readonly DataID[];
  outputVersions: readonly DataVersion[];
  unchanged: boolean;
};

/**
 * The record of the last resolution of an invocation signature. Recorded
 * versions carry their namespace: generated versions (even, from the run
 * counter) for data produced by the graph, source versions (odd, via
 * versionToSourceDataVersion) for caller-versioned sources, or negative
 * sentinels.
 */
type InvocationRecord = {
  invocationID: InvocationID;
  procID: ProcID;
  inputIDs: readonly DataID[];
  inputVersions: readonly DataVersion[];
  outputIDs: readonly DataID[];
  outputVersions: readonly DataVersion[];
  // The run index of the last resolution that saw this record; records
  // untouched for long are evicted.
  lastTouchedRun: number;
};

/**
 * A single run's resolution session against a graph. Resolutions read only
 * records committed by previous successful runs; records produced by this
 * run are buffered and written by `commit()`, so a failed run leaves no
 * records for invocations that never completed.
 */
export type GraphRun = {
  /**
   * The version assigned to data produced by this run.
   */
  readonly version: DataVersion;
  /**
   * Resolves an invocation draft against the recorded history. Assigns data
   * IDs and versions to unresolved outputs, and reports whether the
   * invocation is unchanged since its last recorded resolution.
   * @param draft The invocation draft to resolve.
   * @returns The resolved output IDs and versions, and the unchanged flag.
   */
  resolve(draft: InvocationDraft): ResolvedInvocation;
  /**
   * Commits the records produced by this run's resolutions. It must be
   * called only after every invocation of the run finished successfully, so
   * that records always describe content that was actually produced.
   */
  commit(): void;
  /**
   * Drops the committed record for a draft whose invocation failed after
   * possibly writing part of its outputs, so the next submission re-executes
   * it instead of trusting the record.
   * @param draft The draft of the failed invocation.
   */
  invalidate(draft: InvocationDraft): void;
};

// A record untouched for this many runs is evicted (checked every
// sweepIntervalRuns) so that a long-lived graph does not accumulate records
// for wirings and data objects that no longer exist. Eviction only costs a
// re-execution on the next matching submission; it can never cause a wrong
// skip.
const recordMaxAgeRuns = 256;
const sweepIntervalRuns = 32;

/**
 * A persistent dependency graph that tracks data identities and versions
 * across runs. It stores no data values; it only answers whether an
 * invocation would produce the same outputs as its last recorded resolution.
 */
export class Graph {
  #externalDataToDataID: WeakMap<object, DataID> = new WeakMap();
  #generateDataID: () => DataID = idGenerator((x: number) => x as DataID);

  #invocations: HashTable<InvocationSignature, InvocationRecord> =
    new HashTable(
      hashInvocationSignature,
      equalsInvocationSignature,
    );
  #generateInvocationID: () => InvocationID = idGenerator((x: number) =>
    x as InvocationID
  );

  // Generated versions are even so that they are disjoint from the odd
  // caller-managed source versions (see versionToSourceDataVersion).
  #currentDataVersion: DataVersion = 0 as DataVersion;
  #runIndex = 0;

  /**
   * Starts a new run. Versions assigned to outputs produced by the run are
   * distinguished from those of all previous runs.
   * @returns The resolution session of the run.
   */
  beginRun(): GraphRun {
    this.#runIndex += 1;
    this.#currentDataVersion = runIndexToOutputDataVersion(this.#runIndex);
    if (this.#runIndex % sweepIntervalRuns === 0) {
      this.#sweep();
    }

    const version = this.#currentDataVersion;
    const runIndex = this.#runIndex;
    const pending: [InvocationSignature, InvocationRecord][] = [];
    return {
      version,
      resolve: (draft) => this.#resolve(draft, version, runIndex, pending),
      commit: () => {
        for (const [signature, record] of pending) {
          this.#invocations.set(signature, record);
        }
        pending.length = 0;
      },
      invalidate: (draft) => {
        this.#invocations.delete(signatureOf(draft));
      },
    };
  }

  /**
   * Resolves the stable data ID of an external object (or of a provide
   * function, used as the identity of intermediate outputs).
   * @param x The external object.
   * @returns The data ID of the object.
   */
  resolveDataID(x: object): DataID {
    const cached = this.#externalDataToDataID.get(x);
    if (cached != null) {
      return cached;
    }

    const dataID = this.#generateDataID();
    this.#externalDataToDataID.set(x, dataID);
    return dataID;
  }

  #resolve(
    draft: InvocationDraft,
    version: DataVersion,
    runIndex: number,
    pending: [InvocationSignature, InvocationRecord][],
  ): ResolvedInvocation {
    if (
      draft.inputIDs.length !== draft.inputVersions.length ||
      draft.outputIDs.length !== draft.outputVersions.length ||
      draft.outputIDs.length !== draft.providerIDs.length
    ) {
      throw new LogicError("invocation draft IDs and versions do not match");
    }

    const signature = signatureOf(draft);
    const cached = this.#invocations.get(signature);
    if (cached == null) {
      const outputIDs = draft.outputIDs.map((o) =>
        o < 0 ? this.#generateDataID() : o
      );
      const outputVersions = draft.outputVersions.map(() => version);
      pending.push([signature, {
        invocationID: this.#generateInvocationID(),
        procID: draft.procID,
        inputIDs: signature.inputIDs,
        inputVersions: draft.inputVersions.slice(),
        outputIDs,
        outputVersions,
        lastTouchedRun: runIndex,
      }]);
      return { outputIDs, outputVersions, unchanged: false };
    }

    cached.lastTouchedRun = runIndex;

    if (equalsVersionArray(draft.inputVersions, cached.inputVersions)) {
      // With unchanged inputs, a (re-)execution deterministically reproduces
      // the recorded content, so the recorded versions stay accurate even
      // when some output's current content diverged; nothing to update.
      const unchanged = matchUnresolvedVersionArray(
        draft.outputVersions,
        cached.outputVersions,
      );
      return {
        outputIDs: cached.outputIDs,
        outputVersions: cached.outputVersions,
        unchanged,
      };
    }

    const outputVersions = cached.outputVersions.map(() => version);
    pending.push([signature, {
      invocationID: cached.invocationID,
      procID: cached.procID,
      inputIDs: cached.inputIDs,
      inputVersions: draft.inputVersions.slice(),
      outputIDs: cached.outputIDs,
      outputVersions,
      lastTouchedRun: runIndex,
    }]);
    return {
      outputIDs: cached.outputIDs,
      outputVersions,
      unchanged: false,
    };
  }

  #sweep(): void {
    const expired: InvocationSignature[] = [];
    for (const [signature, record] of this.#invocations.entries()) {
      if (this.#runIndex - record.lastTouchedRun > recordMaxAgeRuns) {
        expired.push(signature);
      }
    }
    for (const signature of expired) {
      this.#invocations.delete(signature);
    }
  }
}

function signatureOf(draft: InvocationDraft): InvocationSignature {
  return {
    procID: draft.procID,
    inputIDs: draft.inputIDs.slice(),
    outputIDs: draft.outputIDs.slice(),
    providerIDs: draft.providerIDs.slice(),
  };
}
