import type { Brand } from "./_brand.ts";
import { LogicError } from "./_error.ts";
import { HashTable } from "./_hashtable.ts";
import { idGenerator } from "./_idgenerator.ts";
import { fmix32, mixWord } from "./_murmurhash.ts";

export type ProcID = Brand<number, "procID">;
export type DataID = Brand<number, "dataID">;
export type DataVersion = Brand<number, "dataVersion">;

// Module-private keys through which GraphRun reaches into Graph. They are not
// exported, so these methods stay off the public surface of Graph while
// remaining callable across the two classes in this module.
const resolveInGraph = Symbol("resolveInGraph");
const publishRecords = Symbol("publishRecords");
const deleteRecord = Symbol("deleteRecord");

export const generateProcID: () => ProcID = idGenerator((x: number) =>
  x as ProcID
);

// Negative values are sentinels and never valid resolved IDs/versions.
// Real versions are positive and split into two disjoint namespaces so that
// a caller-managed number can never be mistaken for a generated one:
// versions generated by the run counter are even, and caller-managed source
// versions are mapped to odd values by versionToSourceDataVersion.

// Unresolved value used for intermediate data nodes.
export const unresolvedIntermediateDataID = -1 as DataID;

// A placeholder version acts as a wildcard when matching recorded output versions.
export const unresolvedIntermediateDataVersion = -1 as DataVersion;
// A version for data whose current content is unknown (e.g. a destination
// whose version is not supplied). It never matches any recorded version.
export const unknownDataVersion = -2 as DataVersion;
// A version for data that must be considered changed every time (e.g. a
// source whose version is not supplied). It never equals any version,
// including itself.
export const alwaysChangedDataVersion = -3 as DataVersion;

// Undefined value used for destination slots where providers are not used.
export const undefinedProviderID = -1 as DataID;

/**
 * Maps a caller-managed source version (a non-negative integer) into the
 * graph's version namespace. The given version must be below 2^52.
 * @param version The caller-managed version.
 * @returns The version in the graph's namespace.
 */
export function versionToSourceDataVersion(version: number): DataVersion {
  return (version * 2 + 1) as DataVersion;
}

/**
 * Maps an internal run count into the graph's version namespace. The given
 * runIndex must be below 2^52.
 * @param runIndex The run count.
 * @returns The version in the graph's namespace.
 */
// FIXME: Generated versions are unique only within one Graph. When two
// Contexts write the same destination object, both report plain runIndex*2
// versions, so a claim stored from one Context can numerically match a
// record of the other Context and cause a wrong "unchanged" skip. Sharing a
// destination across Contexts is out of scope for now; salt the generated
// namespace per Graph if it is ever supported.
function runIndexToOutputDataVersion(runIndex: number): DataVersion {
  return (runIndex * 2) as DataVersion;
}

function matchUnresolvedVersion(
  unresolved: DataVersion,
  resolved: DataVersion,
): boolean {
  if (unresolved === unresolvedIntermediateDataVersion) {
    return true;
  }
  if (unresolved < 0 || resolved < 0) {
    return false;
  }

  return unresolved === resolved;
}

function matchUnresolvedVersionArray(
  unresolved: readonly DataVersion[],
  resolved: readonly DataVersion[],
): boolean {
  if (unresolved.length !== resolved.length) {
    return false;
  }

  for (let i = 0; i < unresolved.length; i++) {
    if (!matchUnresolvedVersion(unresolved[i], resolved[i])) {
      return false;
    }
  }

  return true;
}

function equalsVersionArray(
  l: readonly DataVersion[],
  r: readonly DataVersion[],
): boolean {
  if (l.length !== r.length) {
    return false;
  }

  for (let i = 0; i < l.length; i++) {
    // Negative versions are sentinels and never equal anything.
    if (l[i] < 0 || r[i] < 0 || l[i] !== r[i]) {
      return false;
    }
  }

  return true;
}

/**
 * An identity of an invocation across runs: which proc was applied to which
 * data nodes, and which providers back its intermediate outputs. Output IDs
 * of intermediate data are unresolved here so that resubmissions of the
 * same wiring find the same record. Their provider IDs distinguish wirings
 * whose outputs are allocated differently, because a different provider can
 * change the produced content (e.g. procs may change the result depends on
 * the shape of the output buffer).
 */
export type InvocationSignature = {
  procID: ProcID;
  inputIDs: readonly DataID[];
  outputIDs: readonly DataID[];
  providerIDs: readonly DataID[];
};

function hashInvocationSignature(x: InvocationSignature): number {
  let h = 0;
  h = mixWord(h, x.procID | 0);
  h = mixIDArray(h, x.inputIDs);
  h = mixIDArray(h, x.outputIDs);
  h = mixIDArray(h, x.providerIDs);
  return fmix32(h);
}

function mixIDArray(h: number, ids: readonly DataID[]): number {
  for (const id of ids) {
    h = mixWord(h, id | 0);
  }
  return h;
}

function equalsInvocationSignature(
  l: InvocationSignature,
  r: InvocationSignature,
): boolean {
  return l.procID === r.procID &&
    equalsIDArray(l.inputIDs, r.inputIDs) &&
    equalsIDArray(l.outputIDs, r.outputIDs) &&
    equalsIDArray(l.providerIDs, r.providerIDs);
}

function equalsIDArray(l: readonly DataID[], r: readonly DataID[]): boolean {
  if (l.length !== r.length) {
    return false;
  }

  for (let i = 0; i < l.length; i++) {
    if (l[i] !== r[i]) {
      return false;
    }
  }

  return true;
}

/**
 * An invocation to resolve against the graph. Output IDs and versions of
 * intermediate data are unresolved. Versions of destinations are the
 * versions of their current content as known by the caller, otherwise
 * "unknown" sentinels.
 * Provider IDs identify the provide functions of intermediate outputs.
 */
export type InvocationDraft = {
  procID: ProcID;
  inputIDs: readonly DataID[];
  inputVersions: readonly DataVersion[];
  outputIDs: readonly DataID[];
  outputVersions: readonly DataVersion[];
  providerIDs: readonly DataID[];
};

/**
 * The result of resolving an invocation draft. When `unchanged` is true, the
 * invocation would produce outputs identical to the content the recorded
 * versions describe, so executing it is unnecessary as long as that content
 * is still available.
 */
export type ResolvedInvocation = {
  outputIDs: readonly DataID[];
  outputVersions: readonly DataVersion[];
  unchanged: boolean;
};

/**
 * The record of the last resolution of an invocation signature.
 */
type InvocationRecord = {
  inputVersions: readonly DataVersion[];
  outputIDs: readonly DataID[];
  outputVersions: readonly DataVersion[];
};

/**
 * A persistent dependency graph that tracks data identities and versions
 * across runs. It stores no data values; it only answers whether an
 * invocation would produce the same outputs as its last recorded resolution.
 * Only the records resolved by the last committed run are retained.
 */
export class Graph {
  #externalDataToDataID: WeakMap<object, DataID> = new WeakMap();
  #generateDataID: () => DataID = idGenerator((x: number) => x as DataID);

  #invocations: HashTable<InvocationSignature, InvocationRecord> =
    new HashTable(
      hashInvocationSignature,
      equalsInvocationSignature,
    );

  #currentDataVersion: DataVersion = 0 as DataVersion;
  #runIndex = 0;

  /**
   * Starts a new run. Versions assigned to outputs produced by the run are
   * distinguished from those of all previous runs.
   * @returns The resolution session of the run.
   */
  beginRun(): GraphRun {
    this.#runIndex += 1;
    this.#currentDataVersion = runIndexToOutputDataVersion(this.#runIndex);

    return new GraphRun(this, this.#currentDataVersion);
  }

  /**
   * Resolves a draft on behalf of a run. Module-private; called only through
   * the `resolveInGraph` symbol by `GraphRun.resolve`.
   */
  [resolveInGraph](
    draft: InvocationDraft,
    version: DataVersion,
    pending: HashTable<InvocationSignature, InvocationRecord>,
  ): ResolvedInvocation {
    return this.#resolve(draft, version, pending);
  }

  /**
   * Publishes a run's pending records as the committed history, dropping the
   * previous records. Module-private; called only through the
   * `publishRecords` symbol by `GraphRun.commit`.
   */
  [publishRecords](
    pending: HashTable<InvocationSignature, InvocationRecord>,
  ): void {
    this.#invocations = pending;
  }

  /**
   * Drops the committed record for a signature. Module-private; called only
   * through the `deleteRecord` symbol by `GraphRun.invalidate`.
   */
  [deleteRecord](signature: InvocationSignature): void {
    this.#invocations.delete(signature);
  }

  /**
   * Drops all committed records. A run that executes without resolving
   * against the graph may overwrite destination content that the records
   * describe, so they must not be trusted afterwards.
   */
  evictAllRecords(): void {
    this.#invocations = new HashTable(
      hashInvocationSignature,
      equalsInvocationSignature,
    );
  }

  /**
   * Resolves the stable data ID of an external object or of a provide
   * function.
   * @param x The external object.
   * @returns The data ID of the object.
   */
  resolveDataID(x: object): DataID {
    const cached = this.#externalDataToDataID.get(x);
    if (cached != null) {
      return cached;
    }

    const dataID = this.#generateDataID();
    this.#externalDataToDataID.set(x, dataID);
    return dataID;
  }

  #resolve(
    draft: InvocationDraft,
    version: DataVersion,
    pending: HashTable<InvocationSignature, InvocationRecord>,
  ): ResolvedInvocation {
    if (
      draft.inputIDs.length !== draft.inputVersions.length ||
      draft.outputIDs.length !== draft.outputVersions.length ||
      draft.outputIDs.length !== draft.providerIDs.length
    ) {
      throw new LogicError("invocation draft IDs and versions do not match");
    }

    const signature = signatureOf(draft);
    const cached = this.#invocations.get(signature);
    if (cached == null) {
      // Identical wirings within one run must share their generated data
      // IDs; otherwise each duplicate would retain its own buffer while
      // only the last-committed record keeps an ID. A signature misses the
      // committed table consistently within a run, so a pending record
      // found here is always one this run generated.
      const generated = pending.get(signature);
      if (generated != null) {
        return {
          outputIDs: generated.outputIDs,
          outputVersions: generated.outputVersions,
          unchanged: false,
        };
      }

      const outputIDs = draft.outputIDs.map((o) =>
        o < 0 ? this.#generateDataID() : o
      );
      const outputVersions = draft.outputVersions.map(() => version);
      pending.set(signature, {
        inputVersions: draft.inputVersions.slice(),
        outputIDs,
        outputVersions,
      });
      return { outputIDs, outputVersions, unchanged: false };
    }

    if (equalsVersionArray(draft.inputVersions, cached.inputVersions)) {
      // With unchanged inputs, a (re-)execution deterministically reproduces
      // the recorded content, so the recorded versions stay accurate even
      // when some output's current content diverged; the record is carried
      // over unmodified.
      pending.set(signature, cached);
      const unchanged = matchUnresolvedVersionArray(
        draft.outputVersions,
        cached.outputVersions,
      );
      return {
        outputIDs: cached.outputIDs,
        outputVersions: cached.outputVersions,
        unchanged,
      };
    }

    const outputVersions = cached.outputVersions.map(() => version);
    pending.set(signature, {
      inputVersions: draft.inputVersions.slice(),
      outputIDs: cached.outputIDs,
      outputVersions,
    });
    return {
      outputIDs: cached.outputIDs,
      outputVersions,
      unchanged: false,
    };
  }
}

/**
 * A single run's resolution session against a graph. Resolutions read only
 * records committed by previous successful runs; records produced by this
 * run are buffered until `commit()` publishes them, so a failed run leaves
 * the previously committed records exactly as they were.
 */
export class GraphRun {
  readonly #graph: Graph;
  // The records resolved by this run, keyed by signature so that identical
  // drafts within one run resolve identically instead of each minting fresh
  // data IDs.
  readonly #pending: HashTable<InvocationSignature, InvocationRecord>;
  #committed = false;

  /**
   * The version assigned to data produced by this run.
   */
  readonly version: DataVersion;

  /**
   * Constructs a run's resolution session. Only `Graph.beginRun` should call
   * this; it publishes the run's version and the empty pending table.
   * @param graph The graph the run resolves against.
   * @param version The version assigned to data produced by the run.
   */
  constructor(graph: Graph, version: DataVersion) {
    this.#graph = graph;
    this.version = version;
    this.#pending = new HashTable(
      hashInvocationSignature,
      equalsInvocationSignature,
    );
  }

  /**
   * Resolves an invocation draft against the recorded history. Assigns data
   * IDs and versions to unresolved outputs, and reports whether the
   * invocation is unchanged since its last recorded resolution. It must not
   * be called after `commit()`.
   * @param draft The invocation draft to resolve.
   * @returns The resolved output IDs and versions, and the unchanged flag.
   */
  resolve(draft: InvocationDraft): ResolvedInvocation {
    // After commit the pending table is the committed table; a late
    // resolution would silently corrupt the published records.
    if (this.#committed) {
      throw new LogicError("resolve must not be called after commit");
    }
    return this.#graph[resolveInGraph](draft, this.version, this.#pending);
  }

  /**
   * Commits the records produced by this run's resolutions and drops every
   * record this run did not resolve. It must be called only after every
   * invocation of the run finished successfully, so that records always
   * describe content that was actually produced.
   */
  commit(): void {
    if (this.#committed) {
      return;
    }
    this.#committed = true;

    // The table holds exactly this run's resolutions, so publishing it
    // wholesale drops every record the run did not resolve.
    this.#graph[publishRecords](this.#pending);
  }

  /**
   * Drops the committed record for a draft whose invocation failed after
   * possibly writing part of its outputs, so the next submission re-executes
   * it instead of trusting the record.
   * @param draft The draft of the failed invocation.
   */
  invalidate(draft: InvocationDraft): void {
    this.#graph[deleteRecord](signatureOf(draft));
  }
}

function signatureOf(draft: InvocationDraft): InvocationSignature {
  return {
    procID: draft.procID,
    inputIDs: draft.inputIDs.slice(),
    outputIDs: draft.outputIDs.slice(),
    providerIDs: draft.providerIDs.slice(),
  };
}
