name: CI

on:
  schedule:
    - cron: "0 3 * * *"
  push:

jobs:
  check:
    strategy:
      matrix:
        deno-version: [v2.2, v2.x, v1.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}
      - run: deno fmt --check
        if: ${{ matrix.deno-version != 'v1.x' && matrix.deno-version != 'v2.x' }}
      - run: deno lint
        if: ${{ matrix.deno-version != 'v1.x' && matrix.deno-version != 'v2.x' }}
      - run: deno test
